services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ktorjournal
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54333:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

#services:
#  backend:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      PORT: 8080
#      JDBC_URL: "jdbc:postgresql://db:5432"
#      DATABASE: ktorjournal
#      DB_USERNAME: alhussein
#      DB_PASSWORD: admin12345
#    depends_on:
#      - db
#    networks:
#      - postgres-network
#  db:
#    image: postgres
#    environment:
#      POSTGRES_DB: ktorjournal
#      POSTGRES_USER: alhussein
#      POSTGRES_PASSWORD: admin12345
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 1s
#    restart: always
#    volumes:
#      - ./tmp/db:/var/lib/postgresql/data
#    networks:
#      - postgres-network
#
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=admin1234
#    ports:
#      - '5050:80'
#    restart: always
#    networks:
#      - postgres-network
#networks:
#  postgres-network:
#    driver: bridge